WIP: added coverage computation
whylabs/whylogs pull request #101
Opened 2020-12-03 23:34 UTC by lalmei

It is not added to ci yet.

2020-12-03 23:37 UTC, ibackus requested changes
Looks mainly good, but the one issue is the unit tests need to be run separately from the component tests.  I believe you can update existing coverage if pytest gets run twice.

2020-12-03 23:47 UTC, lalmei commented
> Looks mainly good, but the one issue is the unit tests need to be run separately from the component tests. I believe you can update existing coverage if pytest gets run twice.

I will try to see if the coverage data aggregate correctly, if not I say we run together for now, the test are currently rather quick.

2020-12-03 23:54 UTC, ibackus commented
> I will try to see if the coverage data aggregate correctly, if not I say we run together for now, the test are currently rather quick.

Agreed.

2020-12-03 23:54 UTC, ibackus approved these changes

2020-12-04 20:04 UTC, andyndang approved these changes

2020-12-04 20:52 UTC, merged