added tests covering cli methods and vizualizers
whylabs/whylogs pull request #103
Opened 2020-12-11 21:30 UTC by lalmei

2020-12-15 06:15 UTC, andyndang commented on src/whylogs/cli/demo_cli.py
> +            "Would you like to proceed to WhyLogs Playground to see how our data visualization works?",
this should be WhyLabs :)

2020-12-15 23:18 UTC, andyndang requested changes
Minor text change !

2020-12-17 17:11 UTC, lalmei commented on src/whylogs/cli/demo_cli.py
> +            "Would you like to proceed to WhyLogs Playground to see how our data visualization works?",
```suggestion
            "Would you like to proceed to WhyLabs Playground to see how our data visualization works?",
```

2020-12-17 19:23 UTC, andyndang approved these changes

2020-12-17 19:56 UTC, merged