OoV support in BoW metric
whylabs/whylogs pull request #1198
Opened 2023-04-11 16:37 UTC by richard-rogers

## Description

Adds optional out-of-vocabulary counting to `BagOfWordsMetric`. This one uses a slower all-Python Bloom filter.

## Changes
```
vocab = ["a", "b", "c"]
config = BagOfWordsConfig.set_vocabulary(vocab)
resolvers = [
    ResolverSpec(column_name="document", metrics=[MetricSpec(BagOfWordsMetric, config)])
]
schema = DeclarativeSchema(resolvers)
doc = ["a", "b", "c", "1", "2", "a", "c", "2"]
profile = why.log(row={"document": doc}, schema=schema)
```
The vocabulary Bloom filter is saved at `config.filename`. It can be deserialized with BagOfWordsConfig.load_vocabulary(). If a vocabulary is set, the `BagOfWordsMetric` tracks the counts of OoV terms encountered in the logged documents. If no vocabulary is set, the OoV terms are neither counted nor tracked.

## Related

Relates to whylabs/whylogs#1190 which uses a faster C Bloom filter.

- [ ] I have reviewed the [Guidelines for Contributing](CONTRIBUTING.md) and the [Code of Conduct](CODE_OF_CONDUCT.md).

2023-04-21 00:01 UTC, richard-rogers commented on python/whylogs/experimental/extras/nlp_metric.py
> +        if self.vocabulary is not None:  # or other.vcoabulary is not None:
```suggestion
        if self.vocabulary is not None:
```

2023-04-21 18:28 UTC, jamie256 commented on python/pyproject.toml
> +pybloom3-richard = {version = "^0.0.1", optional = true}
Can we move this fork over and rename before taking this dependency?

2023-05-24 19:09 UTC, jamie256 requested changes

2023-05-24 19:09 UTC, jamie256 commented on python/pyproject.toml
> +pybloom3-richard = {version = "^0.0.1", optional = true}
still need the new package whylogs-bloom published. Blocking issue: https://github.com/whylabs/whylogs-bloom/issues/1

2023-05-29 13:05 UTC, closed without merging