Update init to allow suppression
whylabs/whylogs pull request #1362
Opened 2023-09-07 22:54 UTC by naddeoa

The new init system can make for confusing demos for existing users and new use cases. Making this suppression option to allow us to avoid output when we don't need to see it.

This is also the first example that was updated to use init, though its a kind of weird case since we don't actually want to display the output in this context.

2023-09-11 14:35 UTC, FelipeAdachi commented on python/examples/integrations/writers/Single_Image_Tracing_Profile_to_WhyLabs.ipynb
Is feast a dependency for the required extras?
if not, maybe it's from your environment, @naddeoa ?

In any case, maybe we could clear the output from install whylogs

2023-09-12 21:51 UTC, jamie256 commented on python/examples/integrations/writers/Single_Image_Tracing_Profile_to_WhyLabs.ipynb
This is useful to demonstrate the changes, but this example was a side branch I don't think we want to check this file in as a main example.

2023-09-12 21:52 UTC, jamie256 requested changes
Improvement over our current output, thanks!

Let's remove that test example notebook from the PR, otherwise looks good!

2023-09-19 04:35 UTC, naddeoa commented on python/examples/integrations/writers/Single_Image_Tracing_Profile_to_WhyLabs.ipynb
This one isn't the big doc update. This pr was for a one off to get Felipe's example working with init. The other PR shows init better: https://github.com/whylabs/whylogs/pull/1365

2023-09-20 03:06 UTC, jamie256 approved these changes
LGTM!

2023-09-20 03:06 UTC, jamie256 commented on python/test_notebooks/notebook_tests.py
> +    "Single_Image_Tracing_Profile_to_WhyLabs.ipynb",
don't need this now that the notebook file is removed.

2023-09-20 03:07 UTC, merged