Implemented columnMostCommonValueInSetConstraint
whylabs/whylogs pull request #390
Opened 2021-12-21 09:56 UTC by MilenaTrajanoska

## Description

Implemented columnMostCommonValueInSetConstraint

### General Checklist

* [ ] Tests added for this feature/bug
      if it was a bug, test must cover it.
* [ ] Conform by the style guides, by using formatter
* [ ] Documentation updated
* [ ] (optional) Please add a label to your PR

2021-12-30 12:17 UTC, Taxuspt requested changes
Looks good. Just some minor comments

2021-12-30 12:17 UTC, Taxuspt commented on src/whylogs/core/datasetprofile.py
> +                frequent_itmes_summ = colprof.frequent_items.to_summary(max_items=1, min_count=1)
Maybe typo `frequent_items_summ` ?

2021-12-30 12:17 UTC, Taxuspt commented on src/whylogs/core/datasetprofile.py
> +                most_common_val = frequent_itmes_summ.items[0].json_value if frequent_itmes_summ else None
In what condition would this be `None`?

2021-12-30 12:17 UTC, Taxuspt commented on src/whylogs/core/statistics/constraints.py
> +        elif msg.HasField("between") and not msg.HasField("value") and not msg.HasField("second_field") and not msg.HasField("reference_set"):
This if condition could be turned into a function. Maybe sync with @pecop2 in this

2021-12-30 12:17 UTC, Taxuspt commented on tests/unit/core/statistics/test_constraints.py
> +        columnMostCommonValueInSetConstraint(value_set=2.3, verbose=True)
Empty line at the end of the document

2022-01-04 18:11 UTC, jamie256 requested changes
Some conflict to resolve and point this PR to mainline and I'll take another look.

2022-01-10 21:00 UTC, jamie256 approved these changes
LGTM!

2022-01-13 00:05 UTC, merged