Implemented columnValuesNotNullConstraint
whylabs/whylogs pull request #392
Opened 2021-12-21 10:36 UTC by MilenaTrajanoska

## Description

Implemented columnValuesNotNullConstraint

### General Checklist

* [ ] Tests added for this feature/bug
      if it was a bug, test must cover it.
* [ ] Conform by the style guides, by using formatter
* [ ] Documentation updated
* [ ] (optional) Please add a label to your PR

2021-12-30 12:22 UTC, Taxuspt approved these changes

2021-12-30 18:56 UTC, jamie256 requested changes
Approach looks good, can you update to target mainline?

2022-01-04 18:15 UTC, jamie256 requested changes
Few more conflicts to resolve.

2022-01-05 10:18 UTC, richard-rogers requested changes

2022-01-05 10:18 UTC, richard-rogers commented on tests/unit/core/statistics/test_constraints.py
> +
Split this into a separate test?

2022-01-05 10:18 UTC, richard-rogers commented on tests/unit/core/statistics/test_constraints.py
> +    dc = DatasetConstraints(None, summary_constraints={"annual_inc": [nnc1]})
This stanza is repeated a lot. Perhaps make it a fixture or function.

2022-01-11 08:10 UTC, jamie256 approved these changes

2022-01-12 11:29 UTC, richard-rogers approved these changes

2022-01-14 17:10 UTC, merged