MultiColumn Value Constraints
whylabs/whylogs pull request #413
Opened 2022-01-12 13:17 UTC by MilenaTrajanoska

## Description

column_values_A_greater_than_B_constraint
column_values_A_greater_than_equal_B_constraint
column_values_A_less_than_B_constraint
column_values_A_less_than_equal_B_constraint
column_values_A_equal_B_constraint
column_values_A_not_equal_B_constraint
sumOfRowValuesOfMultipleColumnsEqualsConstraint
columnPairValuesInSetConstraint
columnValuesUniqueWithinRow

### General Checklist

* [ ] Tests added for this feature/bug
      if it was a bug, test must cover it.
* [ ] Conform by the style guides, by using formatter
* [ ] Documentation updated
* [ ] (optional) Please add a label to your PR

2022-01-12 14:38 UTC, MilenaTrajanoska commented on tests/unit/core/statistics/test_constraints.py
> -def test_column_values_in_set_constraint(df_lending_club, local_config_path):
These tests were duplicated on mainline

2022-01-20 02:30 UTC, jamie256 requested changes
I think there are other PRs your have before this one, but when ready, please target mainline so it is easier to review (and becomes a mergeable PR).

2022-01-21 08:44 UTC, richard-rogers requested changes

2022-01-21 08:44 UTC, richard-rogers commented on src/whylogs/core/columnprofile.py
> +        if constraints is None:
`self.constraints = constraints or MultiColumnValueConstrataints()`

2022-01-24 21:02 UTC, jamie256 approved these changes

2022-01-25 22:11 UTC, richard-rogers approved these changes

2022-01-26 18:34 UTC, merged