Example notebook for the newly created constraints
whylabs/whylogs pull request #417
Opened 2022-01-17 13:52 UTC by pecop2

## Description

Example jupyter notebook for the new constraints.

### Some of the constraints only work when switched to a certain branch, as not all the PRs are merged to mainline!

### General Checklist

* [ ] Tests added for this feature/bug
      if it was a bug, test must cover it.
* [ ] Conform by the style guides, by using formatter
* [ ] Documentation updated
* [ ] (optional) Please add a label to your PR

2022-01-20 02:41 UTC, jamie256 requested changes
Cool, lots of examples here!

When ready can you update this PR on mainline?

* Can we rename the example file to something more descriptive than suffix of "2". I'm open to suggestions, but you can use something like "More_Constraints" if its hard to think of a good name.
* Can we include a few examples of constraints generation if there are updates there?

2022-01-25 16:38 UTC, jamie256 requested changes
Looks like there is a method import error in the constraints notebook test, can you take a look?

 ```
ImportError: cannot import name 'numberOfRowsConstraint' from 'whylogs.core.statistics.constraints' 
```

2022-01-25 16:42 UTC, pecop2 commented
> Looks like there is a method import error in the constraints notebook test, can you take a look?
> 
> ```
> ImportError: cannot import name 'numberOfRowsConstraint' from 'whylogs.core.statistics.constraints' 
> ```

With 'numberOfRowsConstraint' being a part of the Table shape constraints PR that's not merged yet, that could be the problem.

2022-01-26 23:32 UTC, jamie256 approved these changes

2022-01-26 23:33 UTC, merged