Mapping constraint names to readable format
whylabs/whylogs pull request #432
Opened 2022-02-03 23:01 UTC by pecop2

## Description

Maps used to map certain operations to easily understandable strings. The display_names are fully generated from the constraint value, field, operation etc. Previously created simple "name" property is still existent.

**This is the second approach, different than the one initially proposed**

### General Checklist

* [ ] Tests added for this feature/bug
      if it was a bug, test must cover it.
* [ ] Conform by the style guides, by using formatter
* [ ] Documentation updated
* [ ] (optional) Please add a label to your PR

2022-02-10 09:38 UTC, richard-rogers requested changes

2022-02-10 09:38 UTC, richard-rogers commented on src/whylogs/core/statistics/constraints.py
> +    Op.LT: "ess than",
less than?

2022-02-10 09:38 UTC, richard-rogers commented on src/whylogs/core/statistics/constraints.py
> +    def display_report(self, feature_name: str) -> List[tuple]:
Looks like return type should be `Optional[List[tuple]]`

2022-02-10 09:38 UTC, richard-rogers commented on src/whylogs/core/statistics/constraints.py
> +        cols = "Column" if len(self._display_name_dict["dependent_columns"]) == 1 else "Columns"
Will we need to localize this?

2022-02-10 09:38 UTC, richard-rogers commented on src/whylogs/core/statistics/constraints.py
> +    def to_protobuf(self) -> ValueConstraintMsgs:
Looks like return type should be `Optional[ValueConstraintMsgs]`

2022-02-10 09:38 UTC, richard-rogers commented on src/whylogs/core/statistics/constraints.py
> +    def display_report(self) -> List[tuple]:
`Optional[List[tuple]]`

2022-02-10 09:38 UTC, richard-rogers commented on tests/unit/core/statistics/test_constraints.py
> +    with pytest.raises(ValueError):
parametrize

2022-02-10 09:38 UTC, richard-rogers commented on tests/unit/core/statistics/test_constraints.py
> +    cvisc = columnValuesInSetConstraint(value_set={2, 5, 8})
Can we break this up into smaller functions?

2022-02-10 17:36 UTC, pecop2 commented
Since we already continued with the other approach, should this PR be closed ? @jamie256

2022-03-08 18:36 UTC, jamie256 commented
We implemented a different approach, closing this PR.

2022-03-08 18:36 UTC, closed without merging