Dev/loka/jupyter notebook visualization
whylabs/whylogs pull request #433
Opened 2022-02-08 14:59 UTC by Jirayr-Solvee

## Description

This PR gives ability to get list of visualizations for profiled data inside jupyter notebook

### General Checklist

* [ ] Tests added for this feature/bug
      if it was a bug, test must cover it.
* [ ] Conform by the style guides, by using formatter
* [ ] Documentation updated
* [ ] (optional) Please add a label to your PR

2022-02-15 21:13 UTC, jamie256 commented on src/whylogs/viewer/index-hbs-cdn-all-in-jupyter-full-summary-statistics.html
> +        const {value, newValue, suffixe} = abbreviateNumber(randomNumbers(900000000))
These are still random numbers as placeholders? Let me know when the reports are using the profile data.

2022-02-17 17:55 UTC, jamie256 requested changes
Can we make sure we have axis labels for the double histogram chart (same for any of the new charts).

For the drift reports, can we include thresholds and method used to detect drift (maybe its something in a legend or hover).

2022-02-21 23:12 UTC, jamie256 commented on src/whylogs/viewer/index-hbs-cdn-all-in-jupyter-full-summary-statistics.html
> +        const {value, newValue, suffixe} = abbreviateNumber(randomNumbers(900000000))
fixed

2022-02-22 05:55 UTC, jamie256 requested changes
Thanks for making those fixes, looking better! I like the difference charts :-)

1) The ranges labeled are helpful for the summary_drift_report categories! Can we also add a hover info or line in the legend that references the algorithm used for this test?

2) For the visualization.summary_drift_report(preferred_cell_height="1000px") cell there is a severe drift detected with a value as "undefined" for "uniform_integers" is that correct? If this is a divide by zero case I'd expect it to be same treatment as a max value and no drift detected, or is something else going on?

3) for the visualization.double_histogram(feature_names="uniform_integers") the lable values are useful, can we mention the units? for each axis or some hint on what this is?

2022-02-22 05:58 UTC, jamie256 reviewed
Did we solve the case when comparing distributions that don't align?

2022-03-02 20:01 UTC, FelipeAdachi commented
- **double_histogram**: For all of the mixture features, it seems there's a long tail on the X-axis, all the way to 3.0, when max values go up to 1.2~1.3. We can see an example in the attached image. This sould be reproducible directly from the code in `Profile_Viewer_In_Notebook`.

- **double_histogram**: Another issue on double_histogram is the shape of the bins: in some cases, for the mixture_distributions, the bins have a large width and seem to overlap. The attached image is also an example of that. This sould be reproducible directly from the code in `Profile_Viewer_In_Notebook`

![image-20220301-203413](https://user-images.githubusercontent.com/29715545/156439599-c97301a0-f8eb-4104-b787-9ae31002247b.png)

2022-03-15 16:53 UTC, jamie256 approved these changes

2022-03-15 17:04 UTC, merged