Draft NLP metric
whylabs/whylogs pull request #653
Opened 2022-06-21 12:31 UTC by richard-rogers

## Description

This repository needs 

The commits in this pull request will 

## Changes

- Imperative commit or change title (commit ID) 
  - Add some bullet points to explain the change
- Next commit or change (commit ID)

## Related

Relates to organization/repo#number

Closes organization/repo#number

- [ ] I have reviewed the [Guidelines for Contributing](CONTRIBUTING.md) and the [Code of Conduct](CODE_OF_CONDUCT.md).

2022-06-30 22:42 UTC, TheMellyBee reviewed
Alright, I think I understood most of it and it look ok. Have a couple questions for you though

2022-06-30 22:42 UTC, TheMellyBee commented on python/whylogs/extras/nlp_metric.py
> +        for vector in data.list.objs:  # TODO: batch these
Is this a todo for now or a later iteration?

2022-06-30 22:42 UTC, TheMellyBee commented on python/whylogs/extras/nlp_metric.py
> +    def merge(self, other: "SvdMetric") -> "SvdMetric":
This doesn't appear to actually merge as it doesn't work with the other at all. Was it supposed to?

2022-06-30 22:42 UTC, TheMellyBee commented on python/whylogs/extras/nlp_metric.py
> +    def merge(self, other: "SvdMetric") -> "SvdMetric":
Or does it only work with the over SVDMetric if it's an UpdatableSVGMetric?

2022-06-30 22:43 UTC, TheMellyBee commented on python/whylogs/extras/example.py
> +stop_words = set(
Does this put in any emoji or further special symbols? If so do those need stopped?

2022-07-18 20:50 UTC, jamie256 requested changes
I think we can iterate on this in an experimental module if you restructure it a bit.

It would be great to get some feedback from a partner and a review from someone with more expertise in nlp.

2022-07-18 20:50 UTC, jamie256 commented on python/whylogs/extras/example.py
> +from whylogs.extras.nlp_metric import (
Can we move these to an "experimental" folder instead of "extras"?

2022-07-18 20:50 UTC, jamie256 commented on python/whylogs/extras/nlp_metric.py
> +class SvdMetric(Metric):
I like the metric factoring with separating the svd from the nlp metric, can we add some tests for this and NLPMetric?

2022-07-18 20:50 UTC, jamie256 commented on python/whylogs/extras/nlp_metric.py
> +class NlpMetric(CompoundMetric):
An example notebook that calls this from why.log* would be useful context, I think you basically have that in your example.py modulo the top level api integration and callstack. Also some tests would be useful to better see how this works. Is it easy to configure nlp metrics to be enabled? and how do you want callers to log documents?

2022-08-29 13:17 UTC, closed without merging