Dev/melly/bump version
whylabs/whylogs pull request #691
Opened 2022-07-13 22:44 UTC by TheMellyBee

## Description
Get's the bumpversion ability we had in v0 ported over to v1. This allows our github actions bump the appropriate number while keeping everything in sync

## Changes

- Changes the makefile
- Adds a config file
- Hooks it together in poetry

## Related
#688  #689 

- [ X] I have reviewed the [Guidelines for Contributing](CONTRIBUTING.md) and the [Code of Conduct](CODE_OF_CONDUCT.md).

2022-07-18 18:23 UTC, andyndang commented
Task linked: [CU-2jvp3ky whylogs v1 github automation: publish artifacts automation on release](https://app.clickup.com/t/2jvp3ky)

2022-07-18 19:21 UTC, andyndang commented
Task linked: [CU-2jvp5v4 whylogs v1 github automation: bump version](https://app.clickup.com/t/2jvp5v4)

2022-07-18 20:15 UTC, jamie256 requested changes
python-ci check is failing, can you look into this? https://github.com/whylabs/whylogs/runs/7330598765?check_suite_focus=true#step:9:22

2022-07-18 20:15 UTC, jamie256 commented on python/poetry.lock
> +name = "sphinx-rtd-theme"
Is this required for bump2version?

2022-07-19 15:48 UTC, jamie256 approved these changes
LGTM!

2022-07-19 15:49 UTC, merged