Better whylabs support for logged images
whylabs/whylogs pull request #870
Opened 2022-09-23 08:25 UTC by richard-rogers

This depends on #860 

It adds a resolver to the `ImageMetric` analogous to the `DatasetSchema`'s to create the standard metrics (counts, types, cardinality, etc.) that the visualizer & whylabs seem to require. The logical submetric name is prefixed with a metric type code so that the related metrics can be aggregated into some `ColumnProfileView` when the `ImageMetric` is "uncompounded" to send it to whylabs.

2022-09-23 16:03 UTC, jamie256 requested changes
Left some questions, looks like we have something that should work for WhyLabs upload of image profiles? Can you describe what you verified in the description, or update the notebook example?

2022-09-23 16:03 UTC, jamie256 commented on python/poetry.lock
> +version = "1.6.1"
Why are you updating the poetry.lock file in this PR?

2022-09-23 16:03 UTC, jamie256 commented on python/whylogs/extras/image_metric.py
> +class StandardResolver(ImageResolver):
The name `StandardResolver` is surprisingly generic, maybe something like StandardImageMetricResolver while awkward is easier to read and understand?

2022-09-23 16:03 UTC, jamie256 commented on python/whylogs/extras/image_metric.py
> +    resolver: Resolver = field(default_factory=StandardResolver)
I feel like the class hierarchy is broken (but connected by name) here: a `StandardResolver(ImageResolver)` where the base class is `ImageResolver(ABC)` is getting assigned to a field of type `whylogs.core.resolvers.Resolver`.

Maybe having a StandardImageResolver(Resolver) would reduce the hierarchy by 1 level and simplify as you can define the `prefixes` there if needed.

2022-09-23 16:03 UTC, jamie256 commented on python/whylogs/extras/image_metric.py
> +        metadata = get_pil_image_metadata(dummy_image)  # any EXIF tags will be discovered as images are logged
probably don't need the dummy image path if you can add to the set of things logged.

2022-09-23 16:03 UTC, jamie256 commented on python/whylogs/extras/image_metric.py
> +    default_configs: Optional[ImageMetricConfig] = None,
Adding `schema ` here as optional makes sense, but default_configs as a parameter is confusing, why doesn't the `schema.default_configs` suffice?

2022-09-23 16:03 UTC, jamie256 commented on python/whylogs/api/writer/whylabs.py
> +def _ugly_hack(col_name: str, metric_name: str, metric: CompoundMetric) -> Dict[str, ColumnProfileView]:
better would be to name this for what it is doing, and why it is needed: e.g. back_compat? image metrics backport translation? with a TODO for simplifying it if this is not needed long term.

2022-09-23 16:47 UTC, richard-rogers commented on python/poetry.lock
> +version = "1.6.1"
I had to update my poetry version, and some version bumps came in from mainline in the course of working on this PR.

2022-09-23 16:53 UTC, richard-rogers commented on python/whylogs/extras/image_metric.py
> +    resolver: Resolver = field(default_factory=StandardResolver)
Oops, that's a bug :(  The `ImageMetricConfig::resolver` should be of type `ImageResolver`.  I looked at having `ImageResolver <: Resolver`, but the arguments to `resolve()` want to be different.

2022-09-23 16:55 UTC, richard-rogers commented on python/whylogs/extras/image_metric.py
> +        metadata = get_pil_image_metadata(dummy_image)  # any EXIF tags will be discovered as images are logged
That would be tricky with the allow/forbid sets. Also, SPOT for the image stats :)

2022-09-23 17:01 UTC, richard-rogers commented on python/whylogs/extras/image_metric.py
> +    default_configs: Optional[ImageMetricConfig] = None,
If don't pass a `schema`, you can specify the default config to use in the constructed schema. I would guess the more common case is that you're happy with the default `schema` but want to fiddle with the `ImageMetricConfig`.

2022-09-23 17:02 UTC, richard-rogers commented on python/whylogs/api/writer/whylabs.py
> +def _ugly_hack(col_name: str, metric_name: str, metric: CompoundMetric) -> Dict[str, ColumnProfileView]:
I think writing this function convinced me we need to design something else :(

2022-09-23 17:11 UTC, andyndang commented on python/whylogs/extras/image_metric.py
> +    default_configs: Optional[ImageMetricConfig] = None,
That's just very confusing in terms of API though. Removing API is hard so I'd err on less for now

2022-09-23 18:55 UTC, richard-rogers commented on python/whylogs/extras/image_metric.py
> +    default_configs: Optional[ImageMetricConfig] = None,
For usability, I'd prefer to drop the `schema` argument before dropping the `default_configs`.

2022-09-23 21:17 UTC, jamie256 commented on python/poetry.lock
> +version = "1.6.1"
but you should only have to update poetry.lock if its broken or if you change the set of dependencies in pyproject.toml file?

You didn't update the dependencies in this change, so you should not be needing to update the lock file.

Generally I think we can update the poetry.lock periodically if it hasn't been updated in a while but that is probably better as a standalone maintenance PR.

2022-09-23 21:19 UTC, jamie256 commented on python/whylogs/extras/image_metric.py
> +        metadata = get_pil_image_metadata(dummy_image)  # any EXIF tags will be discovered as images are logged
Can we call get_pil_image_metadata() on the first image logged and do the metric resolution then?

2022-09-23 21:20 UTC, jamie256 commented on python/whylogs/extras/image_metric.py
> +    default_configs: Optional[ImageMetricConfig] = None,
schema is consistent with the other log* APIs, I'd argue for consistency in how we extend things, even if its a little awkward to instantiate a schema just so you can throw a config in there.

2022-09-23 22:34 UTC, richard-rogers commented on python/poetry.lock
> +version = "1.6.1"
It's in sync with mainline now.

2022-09-23 22:35 UTC, richard-rogers commented on python/whylogs/extras/image_metric.py
> +        metadata = get_pil_image_metadata(dummy_image)  # any EXIF tags will be discovered as images are logged
I restructured the code to eliminate the need for the dummy image.

2022-09-23 22:36 UTC, richard-rogers commented on python/whylogs/extras/image_metric.py
> +    default_configs: Optional[ImageMetricConfig] = None,
Outvoted :)

2022-09-26 16:41 UTC, jamie256 approved these changes
LGTM!

2022-09-26 16:41 UTC, merged