Draft NLP metric
whylabs/whylogs pull request #909
Opened 2022-10-14 08:48 UTC by richard-rogers

Adds
* `VectorComponent` for holding matrices and vectors
* `SvdMetricConfig`, `SvdMetric`, and `UpdatableSvdMetric` for vector-space embeddings
* `NlpConfig`, `NlpMetric`, and `log_nlp` for NLP logging

2022-11-04 21:07 UTC, jamie256 requested changes
Can you clean this up a bit and get the CI green? Then I'll take a more thorough look.

Can you make the example.py an example notebook or test?

2022-11-04 21:07 UTC, jamie256 commented on python/whylogs/extras/example.py
> +# inverted index weighting utility functions
remove code commented out?

2022-11-04 21:07 UTC, jamie256 commented on python/whylogs/extras/example.py
> +        "?",
are lines 65 and 71 different?

2022-12-01 18:58 UTC, jamie256 commented on python/examples/experimental/NLP.ipynb
> +        "pip install whylogs-1.1.7-py3-none-any.whl"
remove the pip install referencing whylogs wheel, you have a working pip install in next cell.

2022-12-01 19:02 UTC, jamie256 approved these changes, later dismissed
Some minor comments, but looks good to try out in experimental mode.

2022-12-01 19:02 UTC, jamie256 commented on python/examples/experimental/NLP.ipynb
> +        "        \"\",\n",
Is this empty string as a stop word?

2022-12-01 22:44 UTC, richard-rogers commented on python/examples/experimental/NLP.ipynb
> +        "        \"\",\n",
Yes, NLTK's tokenizer produces some odd tokens. I augmented the stop word list with the ones I saw to clean it up a bit.

2023-01-09 08:23 UTC, richard-rogers commented on python/whylogs/experimental/core/metrics/nlp_metric.py
> +from copy import deepcopy
Should probably move this to `python/whylogs/experimental/extras`

2023-02-09 02:38 UTC, closed without merging